[package]
name = "either-future"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>"]
edition = "2018"

[dependencies]
futures = "0.1"
either = "1.5"

[dev-dependencies]
tokio01 = { package = "tokio", version = "0.1" }
tokio02 = { package = "tokio", version = "0.2.0-alpha" }
