[package]
name = "either-future"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>"]
edition = "2018"

[dependencies]
either = "1.5"
futures = {version = "0.1", optional = true}

[dev-dependencies]
tokio01 = { package = "tokio", version = "0.1" }
tokio02 = { package = "tokio", version = "0.2.0-alpha"}

[features]
default = ["std_future", "futures_future"]
std_future = []
futures_future = ["futures"]
