[package]
name = "either-future"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>"]
edition = "2018"
license = "ISC"
homepage = "https://github.com/FSMaxB/rust-either-future"
repository = "https://github.com/FSMaxB/rust-either-future"
keywords = ["future", "either"]
description = "An implementation of Future for Either<impl Future, impl Future>."
readme = "README.md"

[dependencies]
either = "1"
futures = {version = "0.1", optional = true}

[dev-dependencies]
tokio01 = { package = "tokio", version = "0.1" }
futures-lite = "1"

[features]
default = ["std_future", "futures_future"]
std_future = []
futures_future = ["futures"]
